### ISSUE TITLE
Images using scale are stretched

### ISSUE THREAD

**Issue by msbt** [crate/cloud-docs#43]
### Documentation feedback

The images on this page that have `:scale: 50%` via https://github.com/crate/cloud-docs/blob/main/docs/tutorials/edge/introduction.rst?plain=1#L310-L312 (and probably all others that use this) are skewed/stretched. I thought that bug was fixed, but apparently it's not. There's a card on the website board which describes possible solutions, please ping me if/when you have bandwidth for that @amotl @matkuliak 
 
- Page title: Introduction
- Page URL: https://cratedb.com/docs/cloud/en/latest/tutorials/edge/introduction.html
- Source: https://github.com/crate/cloud-docs/blob/main/docs/tutorials/edge/introduction.rst

---

**Comment by amotl** [comment]
Hi. Currently, I have no significant bandwidth. What happens when removing `:scale: 50%` altogether?

**Comment by msbt** [comment]
@amotl it will just use only alt + source, like on the first image `<img alt="CrateDB Cloud sign-in screen" src="../_images/start.png">`

width and height attributes would be nice so we don't have layout shifts, but I would prefer those over stretched images ;)

**Comment by amotl** [comment]
Is this related?

- https://github.com/crate/crate-docs-theme/issues/446

**Comment by msbt** [comment]
Ah yes, it might actually, but since there's no proper demo or documentation I can't really tell, but that extension could solve more than one problem!

**Comment by amotl** [comment]
Did you also have a look whether https://myst-parser.readthedocs.io/ can do more than Sphinx itself?

**Comment by matkuliak** [comment]
Hello. Happy to look into this with priority when I come back (thursday).

**Comment by msbt** [comment]
@matkuliak any chance you had time to check this out? Or what is our general plan with the docs and the other template you started building?

**Comment by msbt** [comment]
thanks @matkuliak, will close this for now then
